---
- hosts: jenkins
  become: yes
  become_method: sudo
  become_user: root
  vars_prompt: 
    - name: "jenkins_user"
      prompt: "Enter User Name for jenkins"
      default: jenkins
      private: no

    - name: "jenkins_password"
      prompt: "Enter Password"
      default: Password
      private: yes

  tasks:
  - name: Copy docker repository
    copy: src=files/docker.repo dest=/etc/yum.repos.d

  - name: DO YUM UPDATE to fix conflicts
    yum: name=* state=latest

  - name: Download Jenkins repository
    get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

  - name: Import Jenkins GPG key
    command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: Install required packages for jenkins
    yum: name={{ item }} state=present
    with_items:
      - java-1.7.0-openjdk
      - docker-engine
      - jenkins

  - name: Disable IPv6
    command: "{{ item }}"
    with_items:
      - sysctl -w net.ipv6.conf.all.disable_ipv6=1
      - sysctl -w net.ipv6.conf.default.disable_ipv6=1

  - name: Disable Jenkins setup wizard
    lineinfile: >
      dest=/etc/sysconfig/jenkins
      regexp='JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true"'
      line='JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'

  - name: Add jenkins user to docker group
    shell: usermod -G docker jenkins

  - name: Start servics
    service: name={{ item }} state=started
    with_items:
      - jenkins
      - docker

  # Jenkis start up takes long time
  - pause: seconds=10

  - name: Download jenkins-cli
    get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/usr/local/bin

  - name: Install jenkins plugin
    shell: java -jar /usr/local/bin/jenkins-cli.jar -s http://localhost:8080 install-plugin "{{ item }}"
    with_items:
      - github
      - build-pipeline-plugin
      - docker-build-publish

  - name: Create user
    #shell: echo 'hpsr=new hudson.security.HudsonPrivateSecurityRealm(false); hpsr.createAccount("jenkins", "Password")' | java -jar /usr/local/bin/jenkins-cli.jar -s http://localhost:8080 groovy =
    shell: echo 'hpsr=new hudson.security.HudsonPrivateSecurityRealm(false); hpsr.createAccount("{{ jenkins_user }}", "{{ jenkins_password }}")' | java -jar /usr/local/bin/jenkins-cli.jar -s http://localhost:8080 groovy =

  - name: Copy Jenkins config
    copy: src=files/config.xml dest=/var/lib/jenkins owner=jenkins mode="u+rw,g-wx,o-wx"
    notify: restart jenkins

  handlers:
   - name: restart jenkins
     service: name=jenkins state=restarted
